services:
    volumes:
    - mariadb-data:/bitnami
  moodle:
    image: "bitnami/moodle:3"
    environment:
    - MARIADB_HOST=db1
    - MARIADB_PORT_NUMBER=3306
    - MOODLE_DATABASE_USER=moodle1
    - MOODLE_DATABASE_NAME=moodle
    - MOODLE_DATABASE_PASSWORD=D2wson-4432
    - ALLOW_EMPTY_PASSWORD=no
    ports:
    - 80:80
    volumes:
    - moodle-data:/bitnami
