services:
  mariadb:
    image: "bitnami/mariadb:10.1"
    environment:
    - MARIADB_USER=bn_moodle
    - MARIADB_DATABASE=bitnami_moodle
    - ALLOW_EMPTY_PASSWORD=yes
    volumes:
    - mariadb-data:/bitnami
    port:
    - 3306:3306,internal=true
  moodle:
    image: "bitnami/moodle:3"
    environment:
    - MARIADB_HOST=mariadb
    - MARIADB_PORT_NUMBER=3306
    - MOODLE_DATABASE_USER=bn_moodle
    - MOODLE_DATABASE_NAME=bitnami_moodle
    - ALLOW_EMPTY_PASSWORD=yes
    ports:
    - 443:443
    volumes:
    - moodle-data:/bitnami
