services:
  volumes:
      - 'mariadb_data:/bitnami bitnami/mariadb:3.8.3 
  moodle:
    build: .
    environment:
      - MARIADB_HOST=db1
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle1
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_PASSWORD=D2wson-4432
    ports:
      - '80:8181'
      - '443:8143'
    volumes:
      - 'moodle_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
