services:
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
  moodle:
    image: "bitnami/moodle:3"
    environment:
    - MARIADB_HOST=db1
    - MARIADB_PORT_NUMBER=3306
    - MOODLE_DATABASE_USER=moodle1
    - MOODLE_DATABASE_NAME=moodle
    - MOODLE_DATABASE_PASSWORD=D2wson-4432
    volumes:
    - moodle-data:/bitnami
